name: e_motawif_new
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

  cupertino_icons: ^1.0.8
  go_router: ^12.0.0  # Ensure you use the latest version
  #firebase_core: ^3.12.1
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.0
  provider: ^6.0.5
  sqflite: ^2.4.2
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  string_similarity: ^2.1.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.11.0
  flutter_map: ^4.0.0
  emoji_picker_flutter: ^4.3.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/e_motawif_logo.png
